### ISSUE TITLE
2.4.12 切换场景后，常驻内存的节点，spine 动画没显示了

### ISSUE THREAD

**Issue by walliniY** [smallmain/cocos-enhance-kit#6]
2.4.12 切换场景后，常驻内存的节点，spine 动画没显示了
即使重新加载ui，spine也不展示
必须调用 bundle 的releaseAll 后，重新 加载ui 显示，spine才能够 显示出来

暂时
cc.dynamicAtlasManager.enabled = false;
就不会出现

**Comment by smallmain** [comment]
如果旧版本没有问题，可能与 #8 有关。
