### ISSUE TITLE
Label高DPI 与 缓存模式

### ISSUE THREAD

**Issue by RuffianZhong** [smallmain/cocos-enhance-kit#9]
请教一个问题，这种实现方式是否与缓存模式有关？
版本：2.4.8
使用：
1.替换引擎文件
engine/cocos2d/core/renderer/utils/label/ttf.js
engine/cocos2d/core/renderer/webgl/assemblers/label/2d/ttf.js
2.开启高清文本开关
cc.enableLabelRetina = true;
cc.labelRetinaScale = 2;
问题：
缓存模式 none 正常工作，文本变得清晰，缓存模式：char 模式，无效果
想请教一下，是支持 none 模式吗？还是使用姿势不对？

**Comment by smallmain** [comment]
可能还有其它文件未替换，本身是支持所有模式的。

**Comment by RuffianZhong** [comment]
哪里有文档说明吗？比如需要高清文本需要替换哪些文件？
因为我只想替换这一部分内容，而不是把整个  cocos-enhance-kit 相关的代码都覆盖到到引擎下面

**Comment by smallmain** [comment]
> 哪里有文档说明吗？比如需要高清文本需要替换哪些文件？ 因为我只想替换这一部分内容，而不是把整个 cocos-enhance-kit 相关的代码都覆盖到到引擎下面

定制化的需求需要自己研究哈。
